import view.Printer;

import java.sql.SQLException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {


    public static void main(String[] args) throws SQLException {

        Printer printer = new Printer();
        printer.view();
    }
}
