/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import helper.HelperFunction;
import model.TodoController;
import myDatabase.DBController;
import org.junit.Test;
import view.Printer;

import java.sql.SQLException;
import java.util.ArrayList;

public class AppTest {
    @Test
    public void testAppHasAGreeting() throws SQLException {


    }


}
